### ISSUE TITLE
HppsController shouldn't inherit from ActionController::Base

### ISSUE THREAD

**Issue by metade** [StemboltHQ/solidus-adyen#33]
`Spree::Adyen:: HppsController` currently inherits from `ActionController::Base`:

```
module Spree
  module Adyen
    class HppsController < ::ActionController::Base
      ...
    end
  end
end
```

See: https://github.com/StemboltHQ/solidus-adyen/blob/master/app/controllers/spree/adyen/hpps_controller.rb#L3

It should inherit either from `ApplicationController` or `Spree::StoreController`.

This is a problem for us because we have some logging that we do on each request and ideally this logging would happen on the HPP controller too so that we can debug Adyen payment issues.

**Comment by Dkendal** [comment]
Inheriting from Spree::StoreController should be fine.
